version: '3.8'

services:
  lambda:
    build: .
    ports:
      - "9000:9000"
    environment:
      - STAGE=dev
      - BOOKS_TABLE_NAME=library-shop-api-books-dev
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./src:/var/task/src
    command: ["src/functions/createBook/index.handler"]
    networks:
      - lambda-network

  # Servicio para testing con DynamoDB local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    networks:
      - lambda-network

  # Servicio para crear la tabla DynamoDB local
  dynamodb-setup:
    image: amazon/aws-cli:latest
    depends_on:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-east-1
    command: >
      sh -c "
        aws dynamodb create-table 
        --table-name library-shop-api-books-dev 
        --attribute-definitions AttributeName=id,AttributeType=S AttributeName=isbn,AttributeType=S 
        --key-schema AttributeName=id,KeyType=HASH 
        --global-secondary-indexes 
          IndexName=isbn-index,KeySchema=[{AttributeName=isbn,KeyType=HASH}],Projection={ProjectionType=ALL} 
        --billing-mode PAY_PER_REQUEST 
        --endpoint-url http://dynamodb-local:8000
      "
    networks:
      - lambda-network

networks:
  lambda-network:
    driver: bridge

volumes:
  dynamodb_data:
