# serverless.yml
service: library-shop-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  profile: default

functions:
  hello:
    handler: src/functions/handler.handler